### ISSUE TITLE
NoSuchMethodError when calling inherited interface method with spec

### ISSUE THREAD

**Issue by btj** [fsc4j/fsc4j#23]
Consider the following program:
```java
interface Foo {
    /** @pre | true */
    void foo();
}
abstract class Bar implements Foo {
    void quux() { foo(); }
}
class Main {
    public static void main(String[] args) {
        new Bar() { public void foo() {} }.quux();
    }
}
```
Running this program produces the following output:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void Bar.foo$spec(Foo)'
	at Bar.quux(Main.java:6)
	at Main.main(Main.java:10)
```
Similarly, consider the following program:
```java
interface Foo {
    /** @pre | true */
    default void foo() {}
}
class Bar implements Foo {
    void quux() { foo(); }
}
public class Main {
    public static void main(String[] args) {
        new Bar().quux();
    }
}
```
Running this program produces the following output:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void Bar.foo$spec(Foo)'
	at Bar.quux(Main.java:6)
	at Main.main(Main.java:10)
```

**Comment by btj** [comment]
The call of `foo` in `quux` produces the following bytecode:
```
aload_0
invokestatic Bar.foo$spec(Foo)
```

**Comment by btj** [comment]
The problem is that static interface methods are not inherited ([JLS](https://docs.oracle.com/javase/specs/jls/se13/html/jls-8.html#jls-8.4.8)) ([JVMS](https://docs.oracle.com/javase/specs/jvms/se15/html/jvms-5.html#jvms-5.4.3.3)) by classes that implement the interface or by subinterfaces.
