### ISSUE TITLE
FSC4J crashes with NullPointerException: Cannot invoke "FormalSpecificationClause$Tag.ordinal()" because "clause.tag" is null

### ISSUE THREAD

**Issue by btj** [fsc4j/fsc4j#32]
The program
```java
class Foo {
void bar() {
[5,]
}
```
causes the following exception:
```
!ENTRY org.eclipse.jdt.ui 4 0 2021-12-03 09:34:53.070
!MESSAGE Error in JDT Core during reconcile
!STACK 1
Java Model Exception: java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.ast.FormalSpecificationClause$Tag.ordinal()" because "clause.tag" is null
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:326)
	at [...]
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.ast.FormalSpecificationClause$Tag.ordinal()" because "clause.tag" is null
	at org.eclipse.jdt.internal.compiler.parser.Parser.consumeAnnotations(Parser.java:4947)
	at org.eclipse.jdt.internal.compiler.parser.Parser.consumeEnumHeaderName(Parser.java:3449)
	at org.eclipse.jdt.internal.compiler.parser.Parser.consumeRule(Parser.java:7969)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12533)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parseStatements(Parser.java:13198)
	at org.eclipse.jdt.internal.compiler.parser.Parser$1MethodVisitor.endVisitMethod(Parser.java:13538)
	at org.eclipse.jdt.internal.compiler.parser.Parser$1MethodVisitor.endVisit(Parser.java:13524)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:417)
	at org.eclipse.jdt.internal.compiler.parser.Parser.recoverStatements(Parser.java:13644)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12600)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12889)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.parseStatements(MethodDeclaration.java:228)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.parseMethods(TypeDeclaration.java:1266)
	at org.eclipse.jdt.internal.compiler.parser.Parser.getMethodBodies(Parser.java:11553)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1056)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1108)
	at [...]
```

**Comment by btj** [comment]
The program
```java
class issue32 {
issue32() {
* @mutates | this
* @mutates | bar
foo();
}
}
```
causes a similar crash:
```
!SUBENTRY 1 org.eclipse.jdt.core 4 1005 2021-12-03 09:55:29.672
!MESSAGE Cannot invoke "org.eclipse.jdt.internal.compiler.ast.FormalSpecificationClause$Tag.ordinal()" because "clause.tag" is null
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.internal.compiler.ast.FormalSpecificationClause$Tag.ordinal()" because "clause.tag" is null
	at org.eclipse.jdt.internal.compiler.parser.Parser.consumeAnnotations(Parser.java:4947)
	at org.eclipse.jdt.internal.compiler.parser.Parser.consumeEnumHeaderName(Parser.java:3449)
	at org.eclipse.jdt.internal.compiler.parser.Parser.consumeRule(Parser.java:7969)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12533)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parseStatements(Parser.java:13198)
	at org.eclipse.jdt.internal.compiler.parser.Parser$1MethodVisitor.endVisitMethod(Parser.java:13538)
	at org.eclipse.jdt.internal.compiler.parser.Parser$1MethodVisitor.endVisit(Parser.java:13493)
	at org.eclipse.jdt.internal.compiler.ast.ConstructorDeclaration.traverse(ConstructorDeclaration.java:719)
	at org.eclipse.jdt.internal.compiler.parser.Parser.recoverStatements(Parser.java:13644)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12600)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12639)
	at org.eclipse.jdt.internal.compiler.ast.ConstructorDeclaration.parseStatements(ConstructorDeclaration.java:599)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.parseMethods(TypeDeclaration.java:1266)
	at org.eclipse.jdt.internal.compiler.parser.Parser.getMethodBodies(Parser.java:11553)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1056)
	at org.eclipse.jdt.internal.compiler.Compiler.resolve(Compiler.java:1108)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:282)
	at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:348)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:193)
	at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:94)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:740)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:806)
	at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1319)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:131)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:93)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:90)
	at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:157)
	at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.reconcile(CompositeReconcilingStrategy.java:94)
	at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:107)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:76)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:210)
```
Notice that the crash occurs during recovery (inside `recoverStatements`) and, curiously, while the parser attempts to parse an *enum header*. Apparently, the recovery algorithm inserted an `enum` keyword!

Interestingly, the command-line compiler does not crash; it produces the following errors:
```
----------
1. ERROR in SOURCE_FILE_FULL_PATH (at line 3)
	* @mutates | this
	^
Syntax error on token "*", delete this token
----------
2. ERROR in SOURCE_FILE_FULL_PATH (at line 3)
	* @mutates | this
	           ^
Syntax error on token "|", JAVADOC_FORMAL_PART_START expected
----------
3. ERROR in SOURCE_FILE_FULL_PATH (at line 4)
	* @mutates | bar
	  ^
Syntax error on token "@", delete this token
----------
4. ERROR in SOURCE_FILE_FULL_PATH (at line 4)
	* @mutates | bar
	             ^^^
Syntax error, insert "JAVADOC_FORMAL_PART_END" to complete Modifier
----------
5. ERROR in SOURCE_FILE_FULL_PATH (at line 4)
	* @mutates | bar
	             ^^^
Syntax error, insert "enum Identifier" to complete EnumHeaderName
----------
6. ERROR in SOURCE_FILE_FULL_PATH (at line 4)
	* @mutates | bar
	             ^^^
Syntax error, insert "EnumBody" to complete BlockStatements
----------
6 problems (6 errors)
```
This confirms that Eclipse is guessing that an `enum` keyword is missing from this code.

**Comment by btj** [comment]
For the program
```java
```
the command-line compiler produces the following errors:
```
----------
1. ERROR in SOURCE_FILE_FULL_PATH (at line 3)
	[5,]
	^
Syntax error on token "[", JAVADOC_FORMAL_PART_START expected
----------
2. ERROR in SOURCE_FILE_FULL_PATH (at line 3)
	[5,]
	 ^
Syntax error, insert "JAVADOC_FORMAL_PART_END" to complete Modifier
----------
3. ERROR in SOURCE_FILE_FULL_PATH (at line 3)
	[5,]
	 ^
Syntax error, insert "enum Identifier" to complete EnumHeaderName
----------
4. ERROR in SOURCE_FILE_FULL_PATH (at line 3)
	[5,]
	 ^
Syntax error, insert "EnumBody" to complete BlockStatements
----------
5. ERROR in SOURCE_FILE_FULL_PATH (at line 4)
	}
	^
Syntax error, insert "}" to complete ClassBody
----------
5 problems (5 errors)
```
confirming that, here too, the compiler is guessing that an `enum` keyword is missing.
