### ISSUE TITLE
Representation invariant check failure inside `old` expression leads to spurious "representation invariant must not call nonprivate method" error

### ISSUE THREAD

**Issue by btj** [fsc4j/fsc4j#34]
Consider the following program:
```java
public class Issue34 {
	
	/**
	 * @invar | x != 0
	 */
	private int x;
	
	public int getX() { return x; }
	
	public Issue34() {
		foo();
	}
	
	/**
	 * @post | getX() == old(getX()) + 1
	 */
	private void foo() {
		x++;
	}
	
	public static void main(String[] args) {
		new Issue34();
	}

}
```
When run with assertions enabled, it produces the following output:
```
Exception in thread "main" java.lang.AssertionError: A class representation invariant of an object must not directly or indirectly call a nonprivate method that inspects or mutates the object.
	at Issue34.$classInvariants(Issue34.java:1)
	at Issue34.getX(Issue34.java:8)
	at Issue34.foo$post(Issue34.java:15)
	at Issue34.foo(Issue34.java:19)
	at Issue34.<init>(Issue34.java:11)
	at Issue34.main(Issue34.java:22)
```
This exception is incorrect: The class representation invariant does not call any methods.

**Comment by btj** [comment]
The course of events in the above example is as follows:
1. At the start of the execution of `foo()`, the `old` expression `old(getX())` from `foo`'s postcondition is evaluated.
2. While evaluating `old(getX())`, at the start of executing the `getX()` call, the class representation invariants of the `Issue34` object are checked.
3. At the start of the invariants check, the `Issue34` object's invariants checking state is set to 1.
4. The invariant check fails, throwing an `AssertionError`, but not restoring the invariants checking state.
5. This `AssertionError` is caught: if evaluation of the body of an `old` expression completes with an exception E, this exception is stored but not propagated. The exception is re-thrown only when the `old` expression itself is evaluated as part of evaluating the postcondition (but in this example, the program crashes before this point).
6. After execution of the body of `foo()`, `foo`'s postcondition is evaluated. As part of this, the `getX()` call is evaluated. At the start of the `getX()` call, the class representation invariants are checked again. However, this check detects that the invariants checking state is 1, which it assumes means that a nonpublic method was called from inside a representation invariant.

**Comment by btj** [comment]
The best fix seems to be to change the invariants checking code so that it restores the invariants checking state after the check completes, even if it completes with an exception.
