### ISSUE TITLE
`old` expressions with the same contents sync mutations across different postconditions

### ISSUE THREAD

**Issue by vlad2305m** [fsc4j/fsc4j#38]
```
7 /** 
8  * @post | old(IntStream.range(0, 5)).count() == 5
9  * @post | old(IntStream.range(0, 6)).count() == 6
10 * @post | old( IntStream.range(0, 5)).count() == 5
11 * @post | old(IntStream.range(0, 5)).filter(i -> i % 2 == 0).count() == 3
12 */
```
Fails with error
```
Exception in thread "main" java.lang.IllegalStateException: stream has already been operated upon or closed
	at java.base/java.util.stream.AbstractPipeline.<init>(AbstractPipeline.java:203)
	at java.base/java.util.stream.IntPipeline.<init>(IntPipeline.java:91)
	at java.base/java.util.stream.IntPipeline$StatelessOp.<init>(IntPipeline.java:652)
	at java.base/java.util.stream.IntPipeline$10.<init>(IntPipeline.java:381)
	at java.base/java.util.stream.IntPipeline.filter(IntPipeline.java:380)
	at test.Main.main$post(Main.java:11)
	at test.Main.main(Main.java:16)
```
despite the postcondition being perfectly correct

Moreover, 
```java
    static public int c;
    static public <T> T prt(String msg, T t) {System.out.print(c++); System.out.print(msg); System.out.println(t); return t;}
    /** 
     * @post | prt("new: ",old(prt("old: ",IntStream.range(0, 5)))).count() == 5
     * @post | prt("new: ",old(prt("old: ",IntStream.range(0, 5)))).filter(i -> i % 2 == 0).count() == 3
     */
```
outputs
```
0old: java.util.stream.IntPipeline$Head@6b95977
1new: java.util.stream.IntPipeline$Head@6b95977
2new: java.util.stream.IntPipeline$Head@6b95977
```
which clearly shows that the expression is only evaluated once and the reference to the same object is given to the user twice which breaks consistency

**Comment by btj** [comment]
This is intended behavior. It is good for performance.

The solution for your problem is to write `old(IntStream.range(0, 5).toArray()).length` or `old(IntStream.range(0, 5).collect(Collectors.toList())).size()`.
