### ISSUE TITLE
Multiline lambda in formal part kills source locations, coverage results

### ISSUE THREAD

**Issue by btj** [fsc4j/fsc4j#8]
If a compilation unit contains a Javadoc comment with a formal part containing a lambda expression spread over multiple lines, then incorrect source location information is emitted into the `.class` files.

For example:
```java
class Main {
	/**
	 * @post | java.util.stream.IntStream.range(0, 2).allMatch(i ->
	 *       |     false)
	 */
	public static void main(String[] args) {}
}
```
Running this program with assertions enabled produces the error message
```
Exception in thread "main" java.lang.AssertionError: Postcondition does not hold
	at Main.main$post(multiline_lambdas.java:1)
	at Main.main(multiline_lambdas.java:1)
```
instead of
```
Exception in thread "main" java.lang.AssertionError: Postcondition does not hold
	at Main.main$post(multiline_lambdas.java:3)
	at Main.main(multiline_lambdas.java:6)
```
Furthermore, test coverage results are not shown correctly in Eclipse.

**Comment by btj** [comment]
During overload resolution of the method call for which the lambda expression is an argument, a copy of the lambda expression is made, using the `LambdaExpression.copy` method. This method re-parses the lambda expression to get a copy of the AST. To do so, it initializes a scanner with the compilation unit source code and resets it to the source range of the lambda expression.

The lambda expression will not be parsed correctly because the `*  |` prefixing each Javadoc formal part line will not be skipped. This is because the Javadoc comments information built during the initial parse is no longer available.

This causes the re-parse to end with a syntax error. The syntax reporting logic then kicks in. However, it was not designed to run during a re-parse. It start by saving line separator positions to the `CompilationResult` object. However, the scanner's line separator positions are not set, causing the line separator position information to be lost. The code generation phase uses the line separator position information from the `CompilationUnit` to generate the source line information to be emitted to the `.class` file.
